spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource-factory?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: qwerty
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        cluster-name: nanjing

    sentinel:
      transport:
        dashboard: localhost:8080


  application:
    name: user-center




#server:
#  port: 8080

