server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource-factory?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: qwerty
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: content-center

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: beijing

    sentinel:
      transport:
        dashboard: localhost:8080
      filter:   #关闭sentinel对服务的保护
        enabled: false


#logging:
#  level:
    #前提是需开启feign的日志级别为full
#    com.asule.service.UserCenterFeignClient: debug

#feign
feign:
  client:
    config:
        user-center:    #调用该服务时，设定feign的日志级别。若要设置全局，服务名设置为：default。
            loggerLevel: full
  #为feign添加sentinel支持
  sentinel:
      enabled: true

  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 20000
    # feign单个路径的最大连接数
    max-connections-per-route: 5000



#默认通过http暴露的只有health和info，这里罗列出所有。
management:
  endpoints:
    web:
      exposure:
        include: '*'
#显示详细的health状态，默认只有UP/DOWN
  endpoint:
    health:
      show-details: always